In [5]:
import pandas as pd

df = pd.read_csv('ELAN_outputs/bench_1_mouse_keyboard.txt', sep='\t', header=None,
                 names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])

# Drop participant column
df = df[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

df.head()

# Average duration per task type
result = df.groupby('value')['dur_s'].mean()
result.index = result.index.str.extract(r'(\d+)')[0].astype(int).rename('value')
result = result.sort_index()
print(result)

value
1     1.8896
2     1.8364
3     3.6040
4     0.7144
5     0.5604
6     0.6858
7     1.8678
8     1.3506
9     5.1932
10    0.6572
11    3.4482
12    4.8768
13    2.6378
14    2.8200
Name: dur_s, dtype: float64

In [4]:
df.head(100)

       tier  begin_s    end_s  dur_s    value
0   default    3.134    5.975  2.841   task_1
1   default    6.709    8.845  2.136   task_1
2   default    9.027    9.901  0.874   task_1
3   default   10.201   11.265  1.064   task_1
4   default   12.363   14.896  2.533   task_1
..      ...      ...      ...    ...      ...
65  default  203.592  206.864  3.272  task_14
66  default  206.948  209.316  2.368  task_14
67  default  209.380  211.694  2.314  task_14
68  default  211.722  213.815  2.093  task_14
69  default  213.936  217.989  4.053  task_14

[70 rows x 5 columns]

In [6]:
import pandas as pd

df_voice = pd.read_csv('ELAN_outputs/bench_1_voice.txt', sep='\t', header=None,
                 names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])

# Drop participant column
df_voice = df_voice[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

df_voice.head()

# Average duration per task type
result = df_voice.groupby('value')['dur_s'].mean()
result.index = result.index.str.extract(r'(\d+)')[0].astype(int).rename('value')
result = result.sort_index()
print(result)

value
1       6.0224
2      22.3778
3      61.8802
4       6.5426
5      10.6210
6      13.4158
7      39.5026
8      42.9202
9      42.9708
10     17.6406
11     51.9272
12     58.0424
13     54.5272
14    112.2758
Name: dur_s, dtype: float64

In [8]:
df_voice.head(100)

       tier   begin_s     end_s    dur_s    value
0   default     6.365    12.178    5.813   task_1
1   default    13.574    15.747    2.173   task_1
2   default    17.077    31.052   13.975   task_1
3   default    33.830    36.221    2.391   task_1
4   default    37.996    43.756    5.760   task_1
..      ...       ...       ...      ...      ...
65  default  2824.715  2889.492   64.777  task_14
66  default  2990.870  3056.685   65.815  task_14
67  default  3058.884  3156.388   97.504  task_14
68  default  3164.810  3331.958  167.148  task_14
69  default  3339.610  3505.745  166.135  task_14

[70 rows x 5 columns]

In [11]:
import pandas as pd

# Mouse/keyboard
df_mouse = pd.read_csv('ELAN_outputs/bench_1_mouse_keyboard.txt', sep='\t', header=None,
                 names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_mouse = df_mouse[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_mouse = df_mouse.groupby('value')['dur_s'].mean().reset_index()
result_mouse['task_num'] = result_mouse['value'].str.extract(r'(\d+)').astype(int)
result_mouse = result_mouse.sort_values('task_num').rename(columns={'dur_s': 'mouse_s'})

# Voice
df_voice = pd.read_csv('ELAN_outputs/bench_1_voice.txt', sep='\t', header=None,
                 names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_voice = df_voice[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_voice = df_voice.groupby('value')['dur_s'].mean().reset_index()
result_voice['task_num'] = result_voice['value'].str.extract(r'(\d+)').astype(int)
result_voice = result_voice.sort_values('task_num').rename(columns={'dur_s': 'voice_s'})

# Merge and calculate percentage increase
combined = result_mouse.merge(result_voice[['task_num', 'voice_s']], on='task_num')
combined['pct_increase'] = ((combined['voice_s'] - combined['mouse_s']) / combined['mouse_s']) * 100

print(combined[['value', 'mouse_s', 'voice_s', 'pct_increase']].round(2).to_string(index=False))

  value  mouse_s  voice_s  pct_increase
 task_1     1.89     6.02        218.71
 task_2     1.84    22.38       1118.57
 task_3     3.60    61.88       1616.99
 task_4     0.71     6.54        815.82
 task_5     0.56    10.62       1795.25
 task_6     0.69    13.42       1856.23
 task_7     1.87    39.50       2014.93
 task_8     1.35    42.92       3077.86
 task_9     5.19    42.97        727.44
task_10     0.66    17.64       2584.21
task_11     3.45    51.93       1405.92
task_12     4.88    58.04       1090.17
task_13     2.64    54.53       1967.15
task_14     2.82   112.28       3881.41

In [ ]:
import pandas as pd

# Mouse/keyboard
df_mouse = pd.read_csv('ELAN_outputs/bench_1_mouse_keyboard.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_mouse = df_mouse[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_mouse = df_mouse.groupby('value')['dur_s'].agg(mouse_s='mean', mouse_sd='std').reset_index()
result_mouse['task_num'] = result_mouse['value'].str.extract(r'(\d+)').astype(int)
result_mouse = result_mouse.sort_values('task_num')



# Voice
df_voice = pd.read_csv('ELAN_outputs/bench_1_voice.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_voice = df_voice[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_voice = df_voice.groupby('value')['dur_s'].agg(voice_s='mean', voice_sd='std').reset_index()
result_voice['task_num'] = result_voice['value'].str.extract(r'(\d+)').astype(int)
result_voice = result_voice.sort_values('task_num')

# Merge and calculate percentage increase
combined = result_mouse.merge(result_voice[['task_num', 'voice_s', 'voice_sd']], on='task_num')
# combined['pct_increase'] = ((combined['voice_s'] - combined['mouse_s']) / combined['mouse_s']) * 100
combined['ratio'] = (combined['voice_s'] / combined['mouse_s']).round(1)

# print(combined[['value', 'mouse_s', 'mouse_sd', 'voice_s', 'voice_sd', 'pct_increase']].round(2).to_string(index=False))
print(combined[['value', 'mouse_s', 'mouse_sd', 'voice_s', 'voice_sd', 'ratio']].round(2).to_string(index=False))

KeyError: "['task_num'] not in index"

In [15]:
import pandas as pd

# Mouse/keyboard
df_mouse = pd.read_csv('ELAN_outputs/bench_1_mouse_keyboard.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_mouse = df_mouse[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_mouse = df_mouse.groupby('value')['dur_s'].agg(
    mouse_s='mean',
    mouse_sd='std',
    mouse_max='max'
).reset_index()
result_mouse['task_num'] = result_mouse['value'].str.extract(r'(\d+)').astype(int)
result_mouse = result_mouse.sort_values('task_num')

# Voice
df_voice = pd.read_csv('ELAN_outputs/bench_1_voice.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_voice = df_voice[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_voice = df_voice.groupby('value')['dur_s'].agg(
    voice_s='mean',
    voice_sd='std',
    voice_max='max'
).reset_index()
result_voice['task_num'] = result_voice['value'].str.extract(r'(\d+)').astype(int)
result_voice = result_voice.sort_values('task_num')

# Merge and calculate ratio
combined = result_mouse.merge(
    result_voice[['task_num', 'voice_s', 'voice_sd', 'voice_max']], on='task_num'
)
combined['ratio'] = (combined['voice_s'] / combined['mouse_s']).round(1)

print(combined[['value', 'mouse_s', 'mouse_sd', 'mouse_max',
                'voice_s', 'voice_sd', 'voice_max', 'ratio']].round(2).to_string(index=False))

  value  mouse_s  mouse_sd  mouse_max  voice_s  voice_sd  voice_max  ratio
 task_1     1.89      0.88       2.84     6.02      4.78      13.98    3.2
 task_2     1.84      1.23       3.64    22.38      4.24      25.17   12.2
 task_3     3.60      0.67       4.34    61.88      9.42      71.96   17.2
 task_4     0.71      0.50       1.60     6.54      0.61       7.27    9.2
 task_5     0.56      0.06       0.62    10.62      0.34      11.04   19.0
 task_6     0.69      0.11       0.87    13.42      4.44      18.22   19.6
 task_7     1.87      0.77       2.49    39.50      8.36      53.06   21.1
 task_8     1.35      0.61       2.37    42.92      4.26      47.96   31.8
 task_9     5.19      0.93       6.04    42.97      5.67      50.93    8.3
task_10     0.66      0.23       1.03    17.64      4.00      21.12   26.8
task_11     3.45      0.54       4.38    51.93     12.44      67.79   15.1
task_12     4.88      2.34       8.59    58.04      3.57      63.00   11.9
task_13     2.64      0.68       3.82    54.53      9.34      65.33   20.7
task_14     2.82      0.82       4.05   112.28     51.34     167.15   39.8

In [16]:
import pandas as pd

# Mouse/keyboard
df_mouse = pd.read_csv('ELAN_outputs/bench_1_mouse_keyboard.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_mouse = df_mouse[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_mouse = df_mouse.groupby('value')['dur_s'].agg(
    mouse_s='mean',
    mouse_sd='std',
    mouse_max='max'
).reset_index()
result_mouse['mouse_cv'] = (result_mouse['mouse_sd'] / result_mouse['mouse_s'] * 100).round(1)
result_mouse['task_num'] = result_mouse['value'].str.extract(r'(\d+)').astype(int)
result_mouse = result_mouse.sort_values('task_num')

# Voice
df_voice = pd.read_csv('ELAN_outputs/bench_1_voice.txt', sep='\t', header=None,
                       names=['tier', 'participant', 'begin_s', 'end_s', 'dur_s', 'value'])
df_voice = df_voice[['tier', 'begin_s', 'end_s', 'dur_s', 'value']]

result_voice = df_voice.groupby('value')['dur_s'].agg(
    voice_s='mean',
    voice_sd='std',
    voice_max='max'
).reset_index()
result_voice['voice_cv'] = (result_voice['voice_sd'] / result_voice['voice_s'] * 100).round(1)
result_voice['task_num'] = result_voice['value'].str.extract(r'(\d+)').astype(int)
result_voice = result_voice.sort_values('task_num')

# Merge and calculate ratio
combined = result_mouse.merge(
    result_voice[['task_num', 'voice_s', 'voice_sd', 'voice_cv', 'voice_max']], on='task_num'
)
combined['ratio'] = (combined['voice_s'] / combined['mouse_s']).round(1)

print(combined[['value', 
                'mouse_s', 'mouse_sd', 'mouse_cv', 'mouse_max',
                'voice_s', 'voice_sd', 'voice_cv', 'voice_max',
                'ratio']].round(2).to_string(index=False))

  value  mouse_s  mouse_sd  mouse_cv  mouse_max  voice_s  voice_sd  voice_cv  voice_max  ratio
 task_1     1.89      0.88      46.5       2.84     6.02      4.78      79.4      13.98    3.2
 task_2     1.84      1.23      66.7       3.64    22.38      4.24      18.9      25.17   12.2
 task_3     3.60      0.67      18.7       4.34    61.88      9.42      15.2      71.96   17.2
 task_4     0.71      0.50      70.3       1.60     6.54      0.61       9.4       7.27    9.2
 task_5     0.56      0.06      10.4       0.62    10.62      0.34       3.2      11.04   19.0
 task_6     0.69      0.11      15.9       0.87    13.42      4.44      33.1      18.22   19.6
 task_7     1.87      0.77      41.2       2.49    39.50      8.36      21.2      53.06   21.1
 task_8     1.35      0.61      45.5       2.37    42.92      4.26       9.9      47.96   31.8
 task_9     5.19      0.93      17.8       6.04    42.97      5.67      13.2      50.93    8.3
task_10     0.66      0.23      34.4       1.03    17.64      4.00      22.7      21.12   26.8
task_11     3.45      0.54      15.5       4.38    51.93     12.44      24.0      67.79   15.1
task_12     4.88      2.34      47.9       8.59    58.04      3.57       6.1      63.00   11.9
task_13     2.64      0.68      25.9       3.82    54.53      9.34      17.1      65.33   20.7
task_14     2.82      0.82      29.2       4.05   112.28     51.34      45.7     167.15   39.8